name: Create Release and Zip Folder

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set repository name variable
        run: echo "REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)" >> $GITHUB_ENV
      - name: Create distribution folder
        run: mkdir -p "$HOME/${{ env.REPO_NAME }}/dist"

      # build frontend
      - name: Setup Node.js to build extension
        uses: actions/setup-node@v4
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install
      - name: Build extension
        working-directory: ./frontend
        run: |
          rm -Rf dist
          npm run build
          mv dist "$HOME/${{ env.REPO_NAME }}/dist/static"

      # build backend
      - name: Move app folder to zip
        working-directory: ./backend
        run: |
          mv app "$HOME/${{ env.REPO_NAME }}/dist/app"
          mv pyproject.toml "$HOME/${{ env.REPO_NAME }}/dist"
          mv .python-version "$HOME/${{ env.REPO_NAME }}/dist"
          mv uv.lock "$HOME/${{ env.REPO_NAME }}/dist"

      # tagging and release
      - name: Set date and SHA variables
        id: vars
        run: |
          echo "DATE=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
          echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "TAG_NAME=v$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV
          echo "RELEASE_NAME=${{ env.REPO_NAME }}-$(date +'%Y%m%d-%H%M').zip" >> $GITHUB_ENV

      - name: Check the distribution folder
        run: ls -l "$HOME/${{ env.REPO_NAME }}/dist"

      - name: Zip the distribution folder
        run: |
          cd "$HOME/${{ env.REPO_NAME }}/dist"
          zip -r "$HOME/${{ env.RELEASE_NAME }}" .
          cd "$HOME"

      - name: Create and push tag
        run: |
          git tag $TAG_NAME
          git push origin $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release & Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: "${{ env.RELEASE_NAME }}"
          name: "Release v${{ env.DATE }}"
          body: "Release for commit ${{ env.SHA }} on date ${{ env.DATE }}"
          tag_name: "${{ env.TAG_NAME }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
